language: csharp
solution: src/Aardvark.sln
before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel > /dev/null
  - mozroots --import --sync > /dev/null
  - dotnet restore src\Aardvark.Base.Extensions
  - dotnet restore src\Aardvark.Base.Delegates
  - dotnet restore src\Aardvark.Base.Telemetry
  - dotnet restore src\Aardvark.Base.Reporting
  - dotnet restore src\Aardvark.Base.TextParser
  - dotnet restore src\Aardvark.Base.Symbol
script: sh ./build.sh
dist: trusty
