language: csharp
solution: src/Aardvark.sln
before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel > /dev/null
  - mozroots --import --sync > /dev/null
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-sdk-2.1.103
  - dotnet restore src/Aardvark.Base.Extensions
  - dotnet restore src/Aardvark.Base.Delegates
  - dotnet restore src/Aardvark.Base.Telemetry
  - dotnet restore src/Aardvark.Base.Reporting
  - dotnet restore src/Aardvark.Base.TextParser
  - dotnet restore src/Aardvark.Base.Symbol
script: sh ./build.sh
dist: trusty
